name: Build and Deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          echo "Moving into directory"
          cd frontend/flydreamair/
          echo "Installing dependencies..."
          npm install
          echo "Building the project..."
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: production
          folder: frontend/flydreamair/dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

